// Renderers / Shaders /////////////////////////////////////////////////////////////////////
export let ShaderChunk: {
  [name: string]: string;

  alphamap_fragment: string;
  alphamap_pars_fragment: string;
  alphatest_fragment: string;
  aomap_fragment: string;
  aomap_pars_fragment: string;
  begin_vertex: string;
  beginnormal_vertex: string;
  bsdfs: string;
  bumpmap_pars_fragment: string;
  clipping_planes_fragment: string;
  clipping_planes_pars_fragment: string;
  clipping_planes_pars_vertex: string;
  clipping_planes_vertex: string;
  color_fragment: string;
  color_pars_fragment: string;
  color_pars_vertex: string;
  color_vertex: string;
  common: string;
  cube_frag: string;
  cube_vert: string;
  cube_uv_reflection_fragment: string;
  defaultnormal_vertex: string;
  depth_frag: string;
  depth_vert: string;
  distanceRGBA_frag: string;
  distanceRGBA_vert: string;
  displacementmap_vertex: string;
  displacementmap_pars_vertex: string;
  emissivemap_fragment: string;
  emissivemap_pars_fragment: string;
  encodings_pars_fragment: string;
  encodings_fragment: string;
  envmap_fragment: string;
  envmap_pars_fragment: string;
  envmap_pars_vertex: string;
  envmap_vertex: string;
  equirect_frag: string;
  equirect_vert: string;
  fog_fragment: string;
  fog_pars_fragment: string;
  linedashed_frag: string;
  linedashed_vert: string;
  lightmap_fragment: string;
  lightmap_pars_fragment: string;
  lights_lambert_vertex: string;
  lights_pars_begin: string;
  lights_pars_map: string;
  lights_phong_fragment: string;
  lights_phong_pars_fragment: string;
  lights_physical_fragment: string;
  lights_physical_pars_fragment: string;
  lights_fragment_begin: string;
  lights_fragment_maps: string;
  lights_fragment_end: string;
  logdepthbuf_fragment: string;
  logdepthbuf_pars_fragment: string;
  logdepthbuf_pars_vertex: string;
  logdepthbuf_vertex: string;
  map_fragment: string;
  map_pars_fragment: string;
  map_particle_fragment: string;
  map_particle_pars_fragment: string;
  meshbasic_frag: string;
  meshbasic_vert: string;
  meshlambert_frag: string;
  meshlambert_vert: string;
  meshphong_frag: string;
  meshphong_vert: string;
  meshphysical_frag: string;
  meshphysical_vert: string;
  metalnessmap_fragment: string;
  metalnessmap_pars_fragment: string;
  morphnormal_vertex: string;
  morphtarget_pars_vertex: string;
  morphtarget_vertex: string;
  normal_flip: string;
  normal_frag: string;
  normal_fragment_begin: string;
  normal_fragment_maps: string;
  normal_vert: string;
  normalmap_pars_fragment: string;
  packing: string;
  points_frag: string;
  points_vert: string;
  shadow_frag: string;
  shadow_vert: string;

  premultiplied_alpha_fragment: string;
  project_vertex: string;
  roughnessmap_fragment: string;
  roughnessmap_pars_fragment: string;
  shadowmap_pars_fragment: string;
  shadowmap_pars_vertex: string;
  shadowmap_vertex: string;
  shadowmask_pars_fragment: string;
  skinbase_vertex: string;
  skinning_pars_vertex: string;
  skinning_vertex: string;
  skinnormal_vertex: string;
  specularmap_fragment: string;
  specularmap_pars_fragment: string;
  tonemapping_fragment: string;
  tonemapping_pars_fragment: string;
  uv2_pars_fragment: string;
  uv2_pars_vertex: string;
  uv2_vertex: string;
  uv_pars_fragment: string;
  uv_pars_vertex: string;
  uv_vertex: string;
  worldpos_vertex: string;
};

export { default as alphamap_fragment } from './ShaderChunk/alphamap_fragment.glsl.js';
export { default as alphamap_pars_fragment } from './ShaderChunk/alphamap_pars_fragment.glsl.js';
export { default as alphatest_fragment } from './ShaderChunk/alphatest_fragment.glsl.js';
export { default as aomap_fragment } from './ShaderChunk/aomap_fragment.glsl.js';
export { default as aomap_pars_fragment } from './ShaderChunk/aomap_pars_fragment.glsl.js';
export { default as begin_vertex } from './ShaderChunk/begin_vertex.glsl.js';
export { default as beginnormal_vertex } from './ShaderChunk/beginnormal_vertex.glsl.js';
export { default as bsdfs } from './ShaderChunk/bsdfs.glsl.js';
export { default as bumpmap_pars_fragment } from './ShaderChunk/bumpmap_pars_fragment.glsl.js';
export { default as clipping_planes_fragment } from './ShaderChunk/clipping_planes_fragment.glsl.js';
export { default as clipping_planes_pars_fragment } from './ShaderChunk/clipping_planes_pars_fragment.glsl.js';
export { default as clipping_planes_pars_vertex } from './ShaderChunk/clipping_planes_pars_vertex.glsl.js';
export { default as clipping_planes_vertex } from './ShaderChunk/clipping_planes_vertex.glsl.js';
export { default as color_fragment } from './ShaderChunk/color_fragment.glsl.js';
export { default as color_pars_fragment } from './ShaderChunk/color_pars_fragment.glsl.js';
export { default as color_pars_vertex } from './ShaderChunk/color_pars_vertex.glsl.js';
export { default as color_vertex } from './ShaderChunk/color_vertex.glsl.js';
export { default as common } from './ShaderChunk/common.glsl.js';
export { default as cube_uv_reflection_fragment } from './ShaderChunk/cube_uv_reflection_fragment.glsl.js';
export { default as default_fragment } from './ShaderChunk/default_fragment.glsl.js';
export { default as default_vertex } from './ShaderChunk/default_vertex.glsl.js';
export { default as defaultnormal_vertex } from './ShaderChunk/defaultnormal_vertex.glsl.js';
export { default as displacementmap_pars_vertex } from './ShaderChunk/displacementmap_pars_vertex.glsl.js';
export { default as displacementmap_vertex } from './ShaderChunk/displacementmap_vertex.glsl.js';
export { default as dithering_fragment } from './ShaderChunk/dithering_fragment.glsl.js';
export { default as dithering_pars_fragment } from './ShaderChunk/dithering_pars_fragment.glsl.js';
export { default as emissivemap_fragment } from './ShaderChunk/emissivemap_fragment.glsl.js';
export { default as emissivemap_pars_fragment } from './ShaderChunk/emissivemap_pars_fragment.glsl.js';
export { default as encodings_fragment } from './ShaderChunk/encodings_fragment.glsl.js';
export { default as encodings_pars_fragment } from './ShaderChunk/encodings_pars_fragment.glsl.js';
export { default as envmap_fragment } from './ShaderChunk/envmap_fragment.glsl.js';
export { default as envmap_pars_fragment } from './ShaderChunk/envmap_pars_fragment.glsl.js';
export { default as envmap_pars_vertex } from './ShaderChunk/envmap_pars_vertex.glsl.js';
export { default as envmap_physical_pars_fragment } from './ShaderChunk/envmap_physical_pars_fragment.glsl.js';
export { default as envmap_vertex } from './ShaderChunk/envmap_vertex.glsl.js';
export { default as fog_fragment } from './ShaderChunk/fog_fragment.glsl.js';
export { default as fog_pars_fragment } from './ShaderChunk/fog_pars_fragment.glsl.js';
export { default as fog_pars_vertex } from './ShaderChunk/fog_pars_vertex.glsl.js';
export { default as fog_vertex } from './ShaderChunk/fog_vertex.glsl.js';
export { default as gradientmap_pars_fragment } from './ShaderChunk/gradientmap_pars_fragment.glsl.js';
export { default as lightmap_fragment } from './ShaderChunk/lightmap_fragment.glsl.js';
export { default as lightmap_pars_fragment } from './ShaderChunk/lightmap_pars_fragment.glsl.js';
export { default as lights_fragment_begin } from './ShaderChunk/lights_fragment_begin.glsl.js';
export { default as lights_fragment_end } from './ShaderChunk/lights_fragment_end.glsl.js';
export { default as lights_fragment_maps } from './ShaderChunk/lights_fragment_maps.glsl.js';
export { default as lights_lambert_vertex } from './ShaderChunk/lights_lambert_vertex.glsl.js';
export { default as lights_pars_begin } from './ShaderChunk/lights_pars_begin.glsl.js';
export { default as lights_phong_fragment } from './ShaderChunk/lights_phong_fragment.glsl.js';
export { default as lights_phong_pars_fragment } from './ShaderChunk/lights_phong_pars_fragment.glsl.js';
export { default as lights_physical_fragment } from './ShaderChunk/lights_physical_fragment.glsl.js';
export { default as lights_physical_pars_fragment } from './ShaderChunk/lights_physical_pars_fragment.glsl.js';
export { default as logdepthbuf_fragment } from './ShaderChunk/logdepthbuf_fragment.glsl.js';
export { default as logdepthbuf_pars_fragment } from './ShaderChunk/logdepthbuf_pars_fragment.glsl.js';
export { default as logdepthbuf_pars_vertex } from './ShaderChunk/logdepthbuf_pars_vertex.glsl.js';
export { default as logdepthbuf_vertex } from './ShaderChunk/logdepthbuf_vertex.glsl.js';
export { default as map_fragment } from './ShaderChunk/map_fragment.glsl.js';
export { default as map_pars_fragment } from './ShaderChunk/map_pars_fragment.glsl.js';
export { default as map_particle_fragment } from './ShaderChunk/map_particle_fragment.glsl.js';
export { default as map_particle_pars_fragment } from './ShaderChunk/map_particle_pars_fragment.glsl.js';
export { default as metalnessmap_fragment } from './ShaderChunk/metalnessmap_fragment.glsl.js';
export { default as metalnessmap_pars_fragment } from './ShaderChunk/metalnessmap_pars_fragment.glsl.js';
export { default as morphnormal_vertex } from './ShaderChunk/morphnormal_vertex.glsl.js';
export { default as morphtarget_pars_vertex } from './ShaderChunk/morphtarget_pars_vertex.glsl.js';
export { default as morphtarget_vertex } from './ShaderChunk/morphtarget_vertex.glsl.js';
export { default as normal_fragment_begin } from './ShaderChunk/normal_fragment_begin.glsl.js';
export { default as normal_fragment_maps } from './ShaderChunk/normal_fragment_maps.glsl.js';
export { default as normalmap_pars_fragment } from './ShaderChunk/normalmap_pars_fragment.glsl.js';
export { default as packing } from './ShaderChunk/packing.glsl.js';
export { default as premultiplied_alpha_fragment } from './ShaderChunk/premultiplied_alpha_fragment.glsl.js';
export { default as project_vertex } from './ShaderChunk/project_vertex.glsl.js';
export { default as roughnessmap_fragment } from './ShaderChunk/roughnessmap_fragment.glsl.js';
export { default as roughnessmap_pars_fragment } from './ShaderChunk/roughnessmap_pars_fragment.glsl.js';
export { default as shadowmap_pars_fragment } from './ShaderChunk/shadowmap_pars_fragment.glsl.js';
export { default as shadowmap_pars_vertex } from './ShaderChunk/shadowmap_pars_vertex.glsl.js';
export { default as shadowmap_vertex } from './ShaderChunk/shadowmap_vertex.glsl.js';
export { default as shadowmask_pars_fragment } from './ShaderChunk/shadowmask_pars_fragment.glsl.js';
export { default as skinbase_vertex } from './ShaderChunk/skinbase_vertex.glsl.js';
export { default as skinning_pars_vertex } from './ShaderChunk/skinning_pars_vertex.glsl.js';
export { default as skinning_vertex } from './ShaderChunk/skinning_vertex.glsl.js';
export { default as skinnormal_vertex } from './ShaderChunk/skinnormal_vertex.glsl.js';
export { default as specularmap_fragment } from './ShaderChunk/specularmap_fragment.glsl.js';
export { default as specularmap_pars_fragment } from './ShaderChunk/specularmap_pars_fragment.glsl.js';
export { default as tonemapping_fragment } from './ShaderChunk/tonemapping_fragment.glsl.js';
export { default as tonemapping_pars_fragment } from './ShaderChunk/tonemapping_pars_fragment.glsl.js';
export { default as uv2_pars_fragment } from './ShaderChunk/uv2_pars_fragment.glsl.js';
export { default as uv2_pars_vertex } from './ShaderChunk/uv2_pars_vertex.glsl.js';
export { default as uv2_vertex } from './ShaderChunk/uv2_vertex.glsl.js';
export { default as uv_pars_fragment } from './ShaderChunk/uv_pars_fragment.glsl.js';
export { default as uv_pars_vertex } from './ShaderChunk/uv_pars_vertex.glsl.js';
export { default as uv_vertex } from './ShaderChunk/uv_vertex.glsl.js';
export { default as worldpos_vertex } from './ShaderChunk/worldpos_vertex.glsl.js';

export { default as background_frag } from './ShaderLib/background_frag.glsl.js';
export { default as background_vert } from './ShaderLib/background_vert.glsl.js';
export { default as cube_frag } from './ShaderLib/cube_frag.glsl.js';
export { default as cube_vert } from './ShaderLib/cube_vert.glsl.js';
export { default as depth_frag } from './ShaderLib/depth_frag.glsl.js';
export { default as depth_vert } from './ShaderLib/depth_vert.glsl.js';
export { default as distanceRGBA_frag } from './ShaderLib/distanceRGBA_frag.glsl.js';
export { default as distanceRGBA_vert } from './ShaderLib/distanceRGBA_vert.glsl.js';
export { default as equirect_frag } from './ShaderLib/equirect_frag.glsl.js';
export { default as equirect_vert } from './ShaderLib/equirect_vert.glsl.js';
export { default as linedashed_frag } from './ShaderLib/linedashed_frag.glsl.js';
export { default as linedashed_vert } from './ShaderLib/linedashed_vert.glsl.js';
export { default as meshbasic_frag } from './ShaderLib/meshbasic_frag.glsl.js';
export { default as meshbasic_vert } from './ShaderLib/meshbasic_vert.glsl.js';
export { default as meshlambert_frag } from './ShaderLib/meshlambert_frag.glsl.js';
export { default as meshlambert_vert } from './ShaderLib/meshlambert_vert.glsl.js';
export { default as meshmatcap_frag } from './ShaderLib/meshmatcap_frag.glsl.js';
export { default as meshmatcap_vert } from './ShaderLib/meshmatcap_vert.glsl.js';
export { default as meshphong_frag } from './ShaderLib/meshphong_frag.glsl.js';
export { default as meshphong_vert } from './ShaderLib/meshphong_vert.glsl.js';
export { default as meshphysical_frag } from './ShaderLib/meshphysical_frag.glsl.js';
export { default as meshphysical_vert } from './ShaderLib/meshphysical_vert.glsl.js';
export { default as normal_frag } from './ShaderLib/normal_frag.glsl.js';
export { default as normal_vert } from './ShaderLib/normal_vert.glsl.js';
export { default as points_frag } from './ShaderLib/points_frag.glsl.js';
export { default as points_vert } from './ShaderLib/points_vert.glsl.js';
export { default as shadow_frag } from './ShaderLib/shadow_frag.glsl.js';
export { default as shadow_vert } from './ShaderLib/shadow_vert.glsl.js';
export { default as sprite_frag } from './ShaderLib/sprite_frag.glsl.js';
export { default as sprite_vert } from './ShaderLib/sprite_vert.glsl.js';
