
var Module = (function() {
    var _scriptDir = import.meta.url;
    
    return (
  function(Module) {
    Module = Module || {};
  
  
  var e;e||(e=typeof Module !== 'undefined' ? Module : {});var aa,ba;e.ready=new Promise(function(a,b){aa=a;ba=b});e.file=e.file||function(a=256){let b=0,c=0,d=new Uint8Array(a);return{contents:function(){return d.slice(0,c)},seek:function(f){b=f},write:function(f){const g=f.byteLength;var k=b+g,h=d.length;h>=k||(k=Math.max(k,h*(1048576>h?2:1.125)>>>0),0!=h&&(k=Math.max(k,256)),h=d,d=new Uint8Array(k),0<c&&d.set(h.subarray(0,c),0));d.set(f,b);b+=g;c=Math.max(c,b);return g}}};
  e.create_buffer=function(a){return e._malloc(a)};e.free_buffer=function(a){return e._free(a)};
  e.create=function(a={}){function b(){null!=h||p||(h=e.create_buffer(d*f*3/2));return h}function c(){null!=m||p||(m=e.create_buffer(d*f*g));return m}const d=a.width,f=a.height,g=a.stride||4;if(!d||!f)throw Error("width and height must be > 0");const k=e.file();let h=null,m=null,p=!1;a=Object.assign({},a);delete a.stride;const q=e.create_encoder(a,function(l,r,u){k.seek(u);l=e.HEAPU8.subarray(l,l+r);return k.write(l)!==l.byteLength});return{memory:function(){return e.HEAPU8},getYUVPointer:b,getRGBPointer:c,
  end:function(){if(p)throw Error("Attempting to end() an encoder that is already finished");p=!0;e.finalize_encoder(q);null!=h&&e.free_buffer(h);null!=m&&e.free_buffer(m);return k.contents()},encodeRGBPointer:function(){const l=c(),r=b();e.encode_rgb(q,l,g,r)},encodeYUVPointer:function(){const l=b();e.encode_yuv(q,l)},encodeRGB:function(l){if(l.length!==d*f*g)throw Error("Expected buffer to be sized (width * height * "+g+")");const r=c(),u=b();e.HEAPU8.set(l,r);e.encode_rgb(q,r,g,u)},encodeYUV:function(l){if(l.length!==
  d*f*3/2)throw Error("Expected buffer to be sized (width * height * 3) / 2");const r=b();e.HEAPU8.set(l,r);e.encode_yuv(q,r)}}};e.locateFile=function(a,b){e.simd&&(a=a.replace(/\.wasm$/i,".simd.wasm"));return e.getWasmPath?e.getWasmPath(a,b,e.simd):b+a};var t={},v;for(v in e)e.hasOwnProperty(v)&&(t[v]=e[v]);var ca=!1,w=!1;ca="object"===typeof window;w="function"===typeof importScripts;var x="",da;
  if(ca||w)w?x=self.location.href:"undefined"!==typeof document&&document.currentScript&&(x=document.currentScript.src),_scriptDir&&(x=_scriptDir),0!==x.indexOf("blob:")?x=x.substr(0,x.lastIndexOf("/")+1):x="",w&&(da=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var y=e.printErr||console.warn.bind(console);for(v in t)t.hasOwnProperty(v)&&(e[v]=t[v]);t=null;var z;e.wasmBinary&&(z=e.wasmBinary);var noExitRuntime;
  e.noExitRuntime&&(noExitRuntime=e.noExitRuntime);"object"!==typeof WebAssembly&&A("no native wasm support detected");var B,ea=!1;
  function C(a,b){var c=D;b=a+b;for(var d="";!(a>=b);){var f=c[a++];if(!f)break;if(f&128){var g=c[a++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var k=c[a++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|c[a++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}
  function fa(a,b,c){var d=D;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0}}
  function ha(a,b){for(var c="",d=0;!(d>=b/2);++d){var f=E[a+2*d>>1];if(0==f)break;c+=String.fromCharCode(f)}return c}function ia(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)E[b>>1]=a.charCodeAt(f),b+=2;E[b>>1]=0;return b-d}function ja(a){return 2*a.length}
  function ka(a,b){for(var c=0,d="";!(c>=b/4);){var f=F[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023)):d+=String.fromCharCode(f)}return d}function la(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}F[b>>2]=g;b+=4;if(b+4>c)break}F[b>>2]=0;return b-d}
  function ma(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var G,na,D,E,oa,F,H,pa,qa;function ra(a){G=a;e.HEAP8=na=new Int8Array(a);e.HEAP16=E=new Int16Array(a);e.HEAP32=F=new Int32Array(a);e.HEAPU8=D=new Uint8Array(a);e.HEAPU16=oa=new Uint16Array(a);e.HEAPU32=H=new Uint32Array(a);e.HEAPF32=pa=new Float32Array(a);e.HEAPF64=qa=new Float64Array(a)}var sa=e.INITIAL_MEMORY||16777216;
  e.wasmMemory?B=e.wasmMemory:B=new WebAssembly.Memory({initial:sa/65536,maximum:32768});B&&(G=B.buffer);sa=G.byteLength;ra(G);var J,ta=[],ua=[],va=[],wa=[];function xa(){var a=e.preRun.shift();ta.unshift(a)}var K=0,ya=null,L=null;e.preloadedImages={};e.preloadedAudios={};function A(a){if(e.onAbort)e.onAbort(a);y(a);ea=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}
  function za(){var a=M;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var M="mp4-encoder.wasm";if(!za()){var Aa=M;M=e.locateFile?e.locateFile(Aa,x):x+Aa}function Ba(){try{if(z)return new Uint8Array(z);if(da)return da(M);throw"both async and sync fetching of the wasm failed";}catch(a){A(a)}}
  function Ca(){return z||!ca&&!w||"function"!==typeof fetch?Promise.resolve().then(Ba):fetch(M,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+M+"'";return a.arrayBuffer()}).catch(function(){return Ba()})}function N(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.K;"number"===typeof c?void 0===b.H?J.get(c)():J.get(c)(b.H):c(void 0===b.H?null:b.H)}}}
  function Da(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ea=void 0;function P(a){for(var b="";D[a];)b+=Ea[D[a++]];return b}var Q={},R={},S={};function Fa(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
  function Ga(a,b){a=Fa(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function Ha(a){var b=Error,c=Ga(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
  var Ia=void 0;function T(a){throw new Ia(a);}var Ja=void 0;function Ka(a,b){function c(h){h=b(h);if(h.length!==d.length)throw new Ja("Mismatched type converter count");for(var m=0;m<d.length;++m)U(d[m],h[m])}var d=[];d.forEach(function(h){S[h]=a});var f=Array(a.length),g=[],k=0;a.forEach(function(h,m){R.hasOwnProperty(h)?f[m]=R[h]:(g.push(h),Q.hasOwnProperty(h)||(Q[h]=[]),Q[h].push(function(){f[m]=R[h];++k;k===g.length&&c(f)}))});0===g.length&&c(f)}
  function U(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||T('type "'+d+'" must have a positive integer typeid pointer');if(R.hasOwnProperty(a)){if(c.L)return;T("Cannot register type '"+d+"' twice")}R[a]=b;delete S[a];Q.hasOwnProperty(a)&&(b=Q[a],delete Q[a],b.forEach(function(f){f()}))}var La=[],V=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
  function Ma(a){4<a&&0===--V[a].I&&(V[a]=void 0,La.push(a))}function W(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=La.length?La.pop():V.length;V[b]={I:1,value:a};return b}}function Na(a){return this.fromWireType(H[a>>2])}function Qa(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
  function Ra(a,b){switch(b){case 2:return function(c){return this.fromWireType(pa[c>>2])};case 3:return function(c){return this.fromWireType(qa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Sa(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Ga(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
  function Ta(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Ua(a,b){var c=e;if(void 0===c[a].F){var d=c[a];c[a]=function(){c[a].F.hasOwnProperty(arguments.length)||T("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].F+")!");return c[a].F[arguments.length].apply(this,arguments)};c[a].F=[];c[a].F[d.J]=d}}
  function Va(a,b,c){e.hasOwnProperty(a)?((void 0===c||void 0!==e[a].F&&void 0!==e[a].F[c])&&T("Cannot register public name '"+a+"' twice"),Ua(a,a),e.hasOwnProperty(c)&&T("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),e[a].F[c]=b):(e[a]=b,void 0!==c&&(e[a].N=c))}function Wa(a,b){for(var c=[],d=0;d<a;d++)c.push(F[(b>>2)+d]);return c}
  function Xa(a,b){0<=a.indexOf("j")||A("Assertion failed: getDynCaller should only be called with i64 sigs");var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];var f;-1!=a.indexOf("j")?f=c&&c.length?e["dynCall_"+a].apply(null,[b].concat(c)):e["dynCall_"+a].call(null,b):f=J.get(b).apply(null,c);return f}}
  function Ya(a,b){a=P(a);var c=-1!=a.indexOf("j")?Xa(a,b):J.get(b);"function"!==typeof c&&T("unknown function pointer with signature "+a+": "+b);return c}var Za=void 0;function $a(a){a=ab(a);var b=P(a);X(a);return b}function bb(a,b){function c(g){f[g]||R[g]||(S[g]?S[g].forEach(c):(d.push(g),f[g]=!0))}var d=[],f={};b.forEach(c);throw new Za(a+": "+d.map($a).join([", "]));}
  function cb(a,b,c){switch(b){case 0:return c?function(d){return na[d]}:function(d){return D[d]};case 1:return c?function(d){return E[d>>1]}:function(d){return oa[d>>1]};case 2:return c?function(d){return F[d>>2]}:function(d){return H[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function Y(a){a||T("Cannot use deleted val. handle = "+a);return V[a].value}function db(a,b){var c=R[a];void 0===c&&T(b+" has unknown type "+$a(a));return c}
  for(var eb={},fb=Array(256),Z=0;256>Z;++Z)fb[Z]=String.fromCharCode(Z);Ea=fb;Ia=e.BindingError=Ha("BindingError");Ja=e.InternalError=Ha("InternalError");e.count_emval_handles=function(){for(var a=0,b=5;b<V.length;++b)void 0!==V[b]&&++a;return a};e.get_first_emval=function(){for(var a=5;a<V.length;++a)if(void 0!==V[a])return V[a];return null};Za=e.UnboundTypeError=Ha("UnboundTypeError");ua.push({K:function(){gb()}});
  var ib={b:function(a,b,c,d){A("Assertion failed: "+(a?C(a,void 0):"")+", at: "+[b?b?C(b,void 0):"":"unknown filename",c,d?d?C(d,void 0):"":"unknown function"])},u:function(a,b,c,d,f){var g=Da(c);b=P(b);U(a,{name:b,fromWireType:function(k){return!!k},toWireType:function(k,h){return h?d:f},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var h=na;else if(2===c)h=E;else if(4===c)h=F;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(h[k>>g])},G:null})},t:function(a,
  b){b=P(b);U(a,{name:b,fromWireType:function(c){var d=V[c].value;Ma(c);return d},toWireType:function(c,d){return W(d)},argPackAdvance:8,readValueFromPointer:Na,G:null})},o:function(a,b,c){c=Da(c);b=P(b);U(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,f){if("number"!==typeof f&&"boolean"!==typeof f)throw new TypeError('Cannot convert "'+Qa(f)+'" to '+this.name);return f},argPackAdvance:8,readValueFromPointer:Ra(b,c),G:null})},l:function(a,b,c,d,f,g){var k=Wa(b,c);a=P(a);f=Ya(d,
  f);Va(a,function(){bb("Cannot call "+a+" due to unbound types",k)},b-1);Ka(k,function(h){var m=a,p=a;h=[h[0],null].concat(h.slice(1));var q=f,l=h.length;2>l&&T("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var r=null!==h[1]&&!1,u=!1,n=1;n<h.length;++n)if(null!==h[n]&&void 0===h[n].G){u=!0;break}var Oa="void"!==h[0].name,I="",O="";for(n=0;n<l-2;++n)I+=(0!==n?", ":"")+"arg"+n,O+=(0!==n?", ":"")+"arg"+n+"Wired";p="return function "+Fa(p)+"("+I+") {\nif (arguments.length !== "+
  (l-2)+") {\nthrowBindingError('function "+p+" called with ' + arguments.length + ' arguments, expected "+(l-2)+" args!');\n}\n";u&&(p+="var destructors = [];\n");var Pa=u?"destructors":"null";I="throwBindingError invoker fn runDestructors retType classParam".split(" ");q=[T,q,g,Ta,h[0],h[1]];r&&(p+="var thisWired = classParam.toWireType("+Pa+", this);\n");for(n=0;n<l-2;++n)p+="var arg"+n+"Wired = argType"+n+".toWireType("+Pa+", arg"+n+"); // "+h[n+2].name+"\n",I.push("argType"+n),q.push(h[n+2]);r&&
  (O="thisWired"+(0<O.length?", ":"")+O);p+=(Oa?"var rv = ":"")+"invoker(fn"+(0<O.length?", ":"")+O+");\n";if(u)p+="runDestructors(destructors);\n";else for(n=r?1:2;n<h.length;++n)l=1===n?"thisWired":"arg"+(n-2)+"Wired",null!==h[n].G&&(p+=l+"_dtor("+l+"); // "+h[n].name+"\n",I.push(l+"_dtor"),q.push(h[n].G));Oa&&(p+="var ret = retType.fromWireType(rv);\nreturn ret;\n");I.push(p+"}\n");h=Sa(I).apply(null,q);n=b-1;if(!e.hasOwnProperty(m))throw new Ja("Replacing nonexistant public symbol");void 0!==e[m].F&&
  void 0!==n?e[m].F[n]=h:(e[m]=h,e[m].J=n);return[]})},j:function(a,b,c,d,f){function g(p){return p}b=P(b);-1===f&&(f=4294967295);var k=Da(c);if(0===d){var h=32-8*c;g=function(p){return p<<h>>>h}}var m=-1!=b.indexOf("unsigned");U(a,{name:b,fromWireType:g,toWireType:function(p,q){if("number"!==typeof q&&"boolean"!==typeof q)throw new TypeError('Cannot convert "'+Qa(q)+'" to '+this.name);if(q<d||q>f)throw new TypeError('Passing a number "'+Qa(q)+'" from JS side to C/C++ side to an argument of type "'+
  b+'", which is outside the valid range ['+d+", "+f+"]!");return m?q>>>0:q|0},argPackAdvance:8,readValueFromPointer:cb(b,k,0!==d),G:null})},h:function(a,b,c){function d(g){g>>=2;var k=H;return new f(G,k[g+1],k[g])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=P(c);U(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{L:!0})},p:function(a,b){b=P(b);var c="std::string"===b;U(a,{name:b,fromWireType:function(d){var f=H[d>>2];if(c)for(var g=
  d+4,k=0;k<=f;++k){var h=d+4+k;if(k==f||0==D[h]){g=g?C(g,h-g):"";if(void 0===m)var m=g;else m+=String.fromCharCode(0),m+=g;g=h+1}}else{m=Array(f);for(k=0;k<f;++k)m[k]=String.fromCharCode(D[d+4+k]);m=m.join("")}X(d);return m},toWireType:function(d,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var g="string"===typeof f;g||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||T("Cannot pass non-string to std::string");var k=(c&&g?function(){for(var p=0,q=0;q<f.length;++q){var l=
  f.charCodeAt(q);55296<=l&&57343>=l&&(l=65536+((l&1023)<<10)|f.charCodeAt(++q)&1023);127>=l?++p:p=2047>=l?p+2:65535>=l?p+3:p+4}return p}:function(){return f.length})(),h=hb(4+k+1);H[h>>2]=k;if(c&&g)fa(f,h+4,k+1);else if(g)for(g=0;g<k;++g){var m=f.charCodeAt(g);255<m&&(X(h),T("String has UTF-16 code units that do not fit in 8 bits"));D[h+4+g]=m}else for(g=0;g<k;++g)D[h+4+g]=f[g];null!==d&&d.push(X,h);return h},argPackAdvance:8,readValueFromPointer:Na,G:function(d){X(d)}})},n:function(a,b,c){c=P(c);
  if(2===b){var d=ha;var f=ia;var g=ja;var k=function(){return oa};var h=1}else 4===b&&(d=ka,f=la,g=ma,k=function(){return H},h=2);U(a,{name:c,fromWireType:function(m){for(var p=H[m>>2],q=k(),l,r=m+4,u=0;u<=p;++u){var n=m+4+u*b;if(u==p||0==q[n>>h])r=d(r,n-r),void 0===l?l=r:(l+=String.fromCharCode(0),l+=r),r=n+b}X(m);return l},toWireType:function(m,p){"string"!==typeof p&&T("Cannot pass non-string to C++ string type "+c);var q=g(p),l=hb(4+q+b);H[l>>2]=q>>h;f(p,l+4,q+b);null!==m&&m.push(X,l);return l},
  argPackAdvance:8,readValueFromPointer:Na,G:function(m){X(m)}})},v:function(a,b){b=P(b);U(a,{M:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},g:function(a,b,c){a=Y(a);b=db(b,"emval::as");var d=[],f=W(d);F[c>>2]=f;return b.toWireType(d,a)},w:function(a,b,c,d){a=Y(a);for(var f=Array(b),g=0;g<b;++g)f[g]=db(F[(c>>2)+g],"parameter "+g);c=Array(b);for(g=0;g<b;++g){var k=f[g];c[g]=k.readValueFromPointer(d);d+=k.argPackAdvance}a=a.apply(void 0,c);return W(a)},c:Ma,e:function(a,
  b){a=Y(a);b=Y(b);return W(a[b])},k:function(a){4<a&&(V[a].I+=1)},i:function(a){a=Y(a);return"number"===typeof a},d:function(a){var b=eb[a];return W(void 0===b?P(a):b)},f:function(a){Ta(V[a].value);Ma(a)},m:function(a,b){a=db(a,"_emval_take_value");a=a.readValueFromPointer(b);return W(a)},q:function(){A()},r:function(a,b,c){D.copyWithin(a,b,b+c)},s:function(a){a>>>=0;var b=D.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<
  d%65536&&(d+=65536-d%65536);a:{try{B.grow(Math.min(2147483648,d)-G.byteLength+65535>>>16);ra(B.buffer);var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},a:B};
  (function(){function a(f){e.asm=f.exports;J=e.asm.x;K--;e.monitorRunDependencies&&e.monitorRunDependencies(K);0==K&&(null!==ya&&(clearInterval(ya),ya=null),L&&(f=L,L=null,f()))}function b(f){a(f.instance)}function c(f){return Ca().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){y("failed to asynchronously prepare wasm: "+g);A(g)})}var d={a:ib};K++;e.monitorRunDependencies&&e.monitorRunDependencies(K);if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return y("Module.instantiateWasm callback failed with error: "+
  f),!1}(function(){return z||"function"!==typeof WebAssembly.instantiateStreaming||za()||"function"!==typeof fetch?c(b):fetch(M,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){y("wasm streaming compile failed: "+g);y("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();
  var gb=e.___wasm_call_ctors=function(){return(gb=e.___wasm_call_ctors=e.asm.y).apply(null,arguments)},hb=e._malloc=function(){return(hb=e._malloc=e.asm.z).apply(null,arguments)},X=e._free=function(){return(X=e._free=e.asm.A).apply(null,arguments)},ab=e.___getTypeName=function(){return(ab=e.___getTypeName=e.asm.B).apply(null,arguments)};e.___embind_register_native_and_builtin_types=function(){return(e.___embind_register_native_and_builtin_types=e.asm.C).apply(null,arguments)};
  e.dynCall_ijiii=function(){return(e.dynCall_ijiii=e.asm.D).apply(null,arguments)};var jb;L=function kb(){jb||lb();jb||(L=kb)};
  function lb(){function a(){if(!jb&&(jb=!0,e.calledRun=!0,!ea)){N(ua);N(va);aa(e);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();wa.unshift(b)}N(wa)}}if(!(0<K)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)xa();N(ta);0<K||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}
  e.run=lb;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();noExitRuntime=!0;lb();
  
  
    return Module.ready
  }
  );
  })();
  export default Module;