import { useState, type ReactNode } from "react";
import {
  Button,
  Card,
  CardBody,
  CardHeader,
  Code,
  Divider,
  Grid,
  H1,
  H2,
  H3,
  Table,
  Text,
} from "cursor/canvas";

const TOC = [
  { id: "overview", label: "Overview" },
  { id: "folders", label: "Major folders" },
  { id: "setup", label: "Setup commands" },
  { id: "runtime", label: "Runtime flow" },
  { id: "first-changes", label: "Safe first changes" },
  { id: "references", label: "References" },
] as const;

const FOLDERS = [
  {
    path: "src/",
    role: "Library source",
    detail:
      "Core classes grouped by domain: core, math, geometries, materials, lights, cameras, loaders, animation, renderers (WebGL/WebGPU), nodes (TSL), scenes, textures, objects.",
  },
  {
    path: "examples/",
    role: "Runnable demos",
    detail:
      "HTML examples plus jsm/ addons (controls, loaders, post-processing, physics helpers). Start here to see APIs in context.",
  },
  {
    path: "build/",
    role: "Bundled output",
    detail:
      "Rollup-generated bundles (three.module.js, three.cjs, WebGPU/TSL builds). Regenerated by npm run build — do not edit or commit.",
  },
  {
    path: "docs/",
    role: "API reference site",
    detail: "JSDoc-generated HTML pages published at threejs.org/docs/. Auto-generated — PRs touching docs/ are blocked for non-collaborators.",
  },
  {
    path: "manual/",
    role: "Learning guides",
    detail: "Long-form tutorials (fundamentals, textures, animation) that complement the API reference.",
  },
  {
    path: "test/",
    role: "Quality gates",
    detail: "Unit tests (Puppeteer) and e2e screenshot tests that guard rendering behavior across examples.",
  },
  {
    path: "utils/",
    role: "Tooling",
    detail: "Rollup config, dev server (server.js), doc builder, and CI helpers.",
  },
  {
    path: "editor/",
    role: "Scene editor app",
    detail: "Browser-based editor for composing scenes; useful when prototyping assets and export flows.",
  },
  {
    path: "devtools/",
    role: "Browser extension",
    detail: "Chrome DevTools panel for inspecting three.js scenes in running pages.",
  },
];

const SETUP_STEPS = [
  {
    title: "Clone (shallow recommended)",
    cmd: "git clone --depth=1 https://github.com/mrdoob/three.js.git\ncd three.js",
    note: "Full history is ~2 GB; shallow clone is enough for development.",
  },
  {
    title: "Install dependencies",
    cmd: "npm ci",
    note: "Uses package-lock.json for reproducible installs.",
  },
  {
    title: "Start dev server",
    cmd: "npm start",
    note: "Runs utils/build/dev.js then serves on https://localhost:8080/ with auto-rebuild of build/ on src/ changes.",
  },
  {
    title: "Verify before pushing",
    cmd: "npm run lint\nnpm run test-unit",
    note: "Full npm test also runs addon unit tests. npm run test-e2e is slow (~200 MB Chromium) and mainly for CI.",
  },
];

const SAFE_CHANGES = [
  {
    area: "Fix a bug in src/",
    steps: [
      "Branch from dev: git checkout -b cursor/my-fix-37a5",
      "Edit the relevant src/ module; run npm start and the closest example",
      "npm run lint && npm run test-unit",
      "Open PR targeting dev — no build/ or docs/ files in the diff",
    ],
    caution: "Protected folders: build/ and docs/ are auto-generated.",
  },
  {
    area: "Add or tweak an example",
    steps: [
      "Copy a similar examples/webgl_*.html as a template",
      "Import from ../build/three.module.js and three/addons/ paths",
      "Keep assets small and properly licensed",
      "Run npm run lint-examples on touched files",
    ],
    caution: "Large models/textures are rarely accepted.",
  },
  {
    area: "Extend an addon in examples/jsm/",
    steps: [
      "Follow patterns in examples/jsm/controls/ or loaders/",
      "Export from examples/jsm/Addons.js when appropriate",
      "npm run lint-addons && npm run test-unit-addons",
    ],
    caution: "Addons ship via npm exports ./addons/* but are not part of the core bundle.",
  },
  {
    area: "Documentation wording",
    steps: [
      "Edit JSDoc comments in src/ — docs rebuild from source",
      "npm run build-docs locally if you need to preview",
    ],
    caution: "Do not hand-edit generated docs/pages/*.html.",
  },
];

function Section({
  id,
  title,
  children,
}: {
  id: string;
  title: string;
  children: ReactNode;
}) {
  return (
    <Card id={id}>
      <CardHeader>
        <H2>{title}</H2>
      </CardHeader>
      <CardBody>{children}</CardBody>
    </Card>
  );
}

export default function DocsCanvasOnboarding() {
  const [activeSection, setActiveSection] = useState<string>("overview");

  return (
    <Grid columns={1} gap={16}>
      <Card>
        <CardHeader>
          <H1>three.js — contributor onboarding</H1>
        </CardHeader>
        <CardBody>
          <Text>
            JavaScript 3D library (WebGL + WebGPU). This canvas maps the repo
            layout, local setup, the render loop mental model, and low-risk
            first contributions. Audience: new contributors and agents exploring
            the codebase.
          </Text>
          <Divider />
          <H3>Jump to section</H3>
          <Grid columns={3} gap={8}>
            {TOC.map((item) => (
              <Button
                key={item.id}
                onClick={() => {
                  setActiveSection(item.id);
                  document.getElementById(item.id)?.scrollIntoView({
                    behavior: "smooth",
                    block: "start",
                  });
                }}
              >
                {activeSection === item.id ? `→ ${item.label}` : item.label}
              </Button>
            ))}
          </Grid>
        </CardBody>
      </Card>

      <Section id="overview" title="Overview">
        <Grid columns={2} gap={12}>
          <Card>
            <CardHeader>
              <H3>What this repo is</H3>
            </CardHeader>
            <CardBody>
              <Text>
                A browser-first 3D engine: scenes, cameras, lights, meshes,
                materials, loaders, animation, and two render backends (WebGL2
                default, WebGPU experimental). Consumers import the published
                npm package three or load build/three.module.js from examples.
              </Text>
            </CardBody>
          </Card>
          <Card>
            <CardHeader>
              <H3>Branch & release model</H3>
            </CardHeader>
            <CardBody>
              <Text>
                Active development happens on dev. Release tags cut from stable
                points; README and package.json currently track v0.184.0.
                Contribution PRs target dev, not main.
              </Text>
            </CardBody>
          </Card>
        </Grid>
        <Divider />
        <Text>
          Entry re-exports: src/Three.js (WebGL public API), src/Three.Core.js
          (renderer-agnostic core), src/Three.WebGPU.js, src/Three.TSL.js (node
          materials). Rollup mirrors these into build/*.module.js.
        </Text>
      </Section>

      <Section id="folders" title="Major folders">
        <Table
          columns={["Path", "Purpose", "Notes"]}
          rows={FOLDERS.map((f) => [f.path, f.role, f.detail])}
        />
        <Divider />
        <H3>src/ layout (high level)</H3>
        <Code language="text">{`src/
├── core/          Object3D, BufferGeometry, Raycaster, Clock
├── math/          Vector*, Matrix*, Quaternion, Color
├── geometries/    BoxGeometry, SphereGeometry, …
├── materials/     MeshStandardMaterial, ShaderMaterial, …
├── lights/        Ambient, Directional, Point, Spot, …
├── cameras/       Perspective, Orthographic, Cube
├── loaders/       GLTF, Texture, Object, File loaders
├── animation/     AnimationMixer, clips, tracks
├── renderers/     WebGLRenderer, WebGPURenderer + webgl/ helpers
├── nodes/         TSL node graph (materials, passes)
├── scenes/        Scene, Fog
├── textures/      Texture types and loaders glue
└── objects/       Mesh, Line, Points, SkinnedMesh, …`}</Code>
      </Section>

      <Section id="setup" title="Setup commands">
        {SETUP_STEPS.map((step) => (
          <Card key={step.title}>
            <CardHeader>
              <H3>{step.title}</H3>
            </CardHeader>
            <CardBody>
              <Code language="bash">{step.cmd}</Code>
              <Text>{step.note}</Text>
            </CardBody>
          </Card>
        ))}
        <Divider />
        <H3>Other useful scripts</H3>
        <Table
          columns={["Command", "What it does"]}
          rows={[
            ["npm run build", "Production Rollup build into build/"],
            ["npm run build-module", "Core module bundle only"],
            ["npm run lint-fix", "Auto-fix ESLint across src, examples, utils"],
            ["npm run build-docs", "Regenerate docs/ + llms txt files"],
            ["npm run test-e2e", "Screenshot regression (CI-scale, slow)"],
          ]}
        />
      </Section>

      <Section id="runtime" title="Runtime flow">
        <Text>
          Typical app loop: create Scene + Camera, populate with Mesh/Object3D
          graph, attach WebGLRenderer to DOM, call render(scene, camera) each
          frame (often via setAnimationLoop).
        </Text>
        <Code language="mermaid">{`flowchart TD
  A["App bootstrap"] --> B["Scene + Camera"]
  B --> C["Lights, Meshes, Loaders"]
  C --> D["WebGLRenderer.render()"]
  D --> E["Animation loop / XR frame"]
  E --> D
  subgraph srcTree ["Key source touchpoints"]
    F["src/scenes/Scene.js"]
    G["src/objects/Mesh.js"]
    H["src/renderers/WebGLRenderer.js"]
  end
  B --> F
  C --> G
  D --> H`}</Code>
        <Divider />
        <H3>Inside WebGLRenderer.render (simplified)</H3>
        <Code language="text">{`1. Update projection / matrices from camera
2. Project scene graph (frustum culling, sort transparent/opaque)
3. Bind programs, uniforms, textures per draw call
4. Issue WebGL draw calls; post-processing passes if configured
5. Present to canvas (color space / tone mapping via WebGLOutput)`}</Code>
        <Text>
          Dev workflow: editing src/ triggers dev.js to rewrite build/*.module.js
          re-exports, so examples hot-reload against your changes without a full
          npm run build.
        </Text>
      </Section>

      <Section id="first-changes" title="Safe first changes">
        <Text>
          Prefer scoped edits with fast feedback loops. Never commit build/ or
          docs/ artifacts — CI rejects protected-folder changes from outside
          collaborators.
        </Text>
        {SAFE_CHANGES.map((item) => (
          <Card key={item.area}>
            <CardHeader>
              <H3>{item.area}</H3>
            </CardHeader>
            <CardBody>
              <Code language="text">
                {item.steps.map((s, i) => `${i + 1}. ${s}`).join("\n")}
              </Code>
              <Text>⚠ {item.caution}</Text>
            </CardBody>
          </Card>
        ))}
        <Divider />
        <H3>Minimal first PR checklist</H3>
        <Code language="text">{`□ Branch from dev
□ One logical change per PR
□ npm run lint — zero errors
□ npm run test-unit — green
□ Relevant example still runs
□ No build/ or docs/ in git diff
□ Mention related issue (#nnnn) in commit message`}</Code>
      </Section>

      <Section id="references" title="References">
        <Table
          columns={["Resource", "Location"]}
          rows={[
            ["Contributing guide", ".github/CONTRIBUTING.md"],
            ["Examples index", "examples/ + https://threejs.org/examples/"],
            ["API docs", "https://threejs.org/docs/"],
            ["Manual", "manual/en/ + https://threejs.org/manual/"],
            ["Migration guide", "GitHub wiki Migration-Guide"],
            ["Forum / Discord", "https://discourse.threejs.org/"],
          ]}
        />
        <Divider />
        <Text>
          Primary maintainers review in spare time — keep PRs focused, include
          screenshots for visual changes, and convert to draft until ready.
        </Text>
      </Section>
    </Grid>
  );
}
