
//addons/utils
import './addons/utils/BufferGeometryUtils.tests.js';
import './addons/utils/ColorUtils.tests.js';
import './addons/utils/GaussianSplatUtils.tests.js';
import './addons/math/ColorSpaces.tests.js';
import './addons/curves/NURBSCurve.tests.js';
import './addons/loaders/FBXLoader.tests.js';
import './addons/loaders/GLTFLoader.tests.js';
import './addons/loaders/HDRLoader.tests.js';
import './addons/loaders/KSPLATLoader.tests.js';
import './addons/loaders/GaussianSplatPLYLoader.tests.js';
import './addons/loaders/SPLATLoader.tests.js';
import './addons/loaders/SPZLoader.tests.js';
import './addons/loaders/USDLoader.tests.js';
import './addons/exporters/USDZExporter.tests.js';
import './addons/tsl/WebGLNodesHandler.tests.js';
import './addons/tsl/GPUTest.tests.js';
import './addons/tsl/TSLDeterminant.tests.js';
import './addons/tsl/TSLFaceForward.tests.js';
import './addons/tsl/TSLGainPcurve.tests.js';
import './addons/tsl/TSLRotate.tests.js';
import './addons/tsl/TSLSinc.tests.js';
import './addons/tsl/TSLBRDF.tests.js';
import './addons/tsl/TSLDepthConversion.tests.js';
import './addons/tsl/TSLColorSpaceConversion.tests.js';
import './addons/tsl/TSLTypeConstructors.tests.js';
import './addons/tsl/TSLBitOps.tests.js';
import './addons/tsl/TSLNoise.tests.js';
